# Challenge 1

In this challenge you will be working on **Pokemon**. You will answer a series of questions in order to practice dataframe calculation, aggregation, and transformation.

![Pokemon](../images/pokemon.jpg)

Follow the instructions below and enter your code.

#### Import all required libraries.

In [1]:
# import libraries
import pandas as pd
import numpy as np

#### Import data set.

Read the dataset `pokemon.csv` into a dataframe called `pokemon`.

*Data set attributed to [Alberto Barradas](https://www.kaggle.com/abcsds/pokemon/)*

In [2]:
# import dataset
pokemon=pd.read_csv('pokemon.csv')

#### Print first 10 rows of `pokemon`.

In [3]:
# your code here
pokemon.sample(10)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
495,446,Munchlax,Normal,NaN,390,135,85,40,40,85,5,4,False
327,302,SableyeMega Sableye,Dark,Ghost,480,50,85,125,85,115,20,3,False
169,155,Cyndaquil,Fire,NaN,309,39,52,43,60,50,65,2,False
792,716,Xerneas,Fairy,NaN,680,126,131,95,131,98,99,6,True
480,432,Purugly,Normal,NaN,452,71,82,64,64,59,112,4,False
630,569,Garbodor,Poison,NaN,474,80,95,82,60,82,75,5,False
73,67,Machoke,Fighting,NaN,405,80,100,70,50,60,45,1,False
708,645,LandorusIncarnate Forme,Ground,Flying,600,89,125,90,115,80,101,5,True
586,527,Woobat,Psychic,Flying,313,55,45,43,55,43,72,5,False
497,448,Lucario,Fighting,Steel,525,70,110,70,115,70,90,4,False

When you look at a data set, you often wonder what each column means. Some open-source data sets provide descriptions of the data set. In many cases, data descriptions are extremely useful for data analysts to perform work efficiently and successfully.

For the `Pokemon.csv` data set, fortunately, the owner provided descriptions which you can see [here](https://www.kaggle.com/abcsds/pokemon/home). For your convenience, we are including the descriptions below. Read the descriptions and understand what each column means. This knowledge is helpful in your work with the data.

| Column | Description |
| --- | --- |
| # | ID for each pokemon |
| Name | Name of each pokemon |
| Type 1 | Each pokemon has a type, this determines weakness/resistance to attacks |
| Type 2 | Some pokemon are dual type and have 2 |
| Total | A general guide to how strong a pokemon is |
| HP | Hit points, or health, defines how much damage a pokemon can withstand before fainting |
| Attack | The base modifier for normal attacks (eg. Scratch, Punch) |
| Defense | The base damage resistance against normal attacks |
| SP Atk | Special attack, the base modifier for special attacks (e.g. fire blast, bubble beam) |
| SP Def | The base damage resistance against special attacks |
| Speed | Determines which pokemon attacks first each round |
| Generation | Number of generation |
| Legendary | True if Legendary Pokemon False if not |

#### Obtain the distinct values across `Type 1` and `Type 2`.

Exctract all the values in `Type 1` and `Type 2`. Then create an array containing the distinct values across both fields.

In [4]:
# your code here
#pokemon.value_counts('Type 1')
#pokemon.value_counts('Type 2')

In [5]:
list_pokemon_t1=list(pokemon['Type 1'].unique()) 
list_pokemon_t2=list(pokemon['Type 2'].unique()) #we've got Nan Value here
list_pokemon_t1,list_pokemon_t2

(['Grass',
  'Fire',
  'Water',
  'Bug',
  'Normal',
  'Poison',
  'Electric',
  'Ground',
  'Fairy',
  'Fighting',
  'Psychic',
  'Rock',
  'Ghost',
  'Ice',
  'Dragon',
  'Dark',
  'Steel',
  'Flying'],
 ['Poison',
  nan,
  'Flying',
  'Dragon',
  'Ground',
  'Fairy',
  'Grass',
  'Fighting',
  'Psychic',
  'Steel',
  'Ice',
  'Rock',
  'Dark',
  'Water',
  'Electric',
  'Fire',
  'Ghost',
  'Bug',
  'Normal'])

In [6]:
pokemon_array= np.concatenate((list_pokemon_t1,list_pokemon_t2), axis=None) #np.array((list_pokemon_t1,list_pokemon_t2), dtype=object)
pokemon_array

array(['Grass', 'Fire', 'Water', 'Bug', 'Normal', 'Poison', 'Electric',
       'Ground', 'Fairy', 'Fighting', 'Psychic', 'Rock', 'Ghost', 'Ice',
       'Dragon', 'Dark', 'Steel', 'Flying', 'Poison', 'nan', 'Flying',
       'Dragon', 'Ground', 'Fairy', 'Grass', 'Fighting', 'Psychic',
       'Steel', 'Ice', 'Rock', 'Dark', 'Water', 'Electric', 'Fire',
       'Ghost', 'Bug', 'Normal'], dtype='<U32')

#### Cleanup `Name` that contain "Mega".

If you have checked out the pokemon names carefully enough, you should have found there are junk texts in the pokemon names which contain "Mega". We want to clean up the pokemon names. For instance, "VenusaurMega Venusaur" should be "Mega Venusaur", and "CharizardMega Charizard X" should be "Mega Charizard X".

In [7]:
# your code here
#visualize those rows first:
#pokemon[pokemon['Name'].str.contains('Mega')]


import re
rule = '[A-Z][a-z]+Mega'
pokemon[pokemon['Name'].str.contains('[A-Z][a-z]+Mega')]



# test transformed data
#I'VE DONE IT BELLOW
#pokemon.head(10)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
12,9,BlastoiseMega Blastoise,Water,NaN,630,79,103,120,135,115,78,1,False
19,15,BeedrillMega Beedrill,Bug,Poison,495,65,150,40,15,80,145,1,False
23,18,PidgeotMega Pidgeot,Normal,Flying,579,83,80,80,135,80,121,1,False
71,65,AlakazamMega Alakazam,Psychic,NaN,590,55,50,65,175,95,150,1,False
87,80,SlowbroMega Slowbro,Water,Psychic,590,95,75,180,130,80,30,1,False
102,94,GengarMega Gengar,Ghost,Poison,600,60,65,80,170,95,130,1,False
124,115,KangaskhanMega Kangaskhan,Normal,NaN,590,105,125,100,60,100,100,1,False
137,127,PinsirMega Pinsir,Bug,Flying,600,65,155,120,65,90,105,1,False
141,130,GyaradosMega Gyarados,Water,Dark,640,95,155,109,70,130,81,1,False
154,142,AerodactylMega Aerodactyl,Rock,Flying,615,80,135,85,70,95,150,1,False
163,150,MewtwoMega Mewtwo X,Psychic,Fighting,780,106,190,100,154,100,130,1,True
164,150,MewtwoMega Mewtwo Y,Psychic,NaN,780,106,150,70,194,120,140,1,True
196,181,AmpharosMega Ampharos,Electric,Dragon,610,90,95,105,165,110,45,2,False
224,208,SteelixMega Steelix,Steel,Ground,610,75,125,230,55,95,30,2,False
229,212,ScizorMega Scizor,Bug,Steel,600,70,150,140,65,100,75,2,False
232,214,HeracrossMega Heracross,Bug,Fighting,600,80,185,115,40,105,75,2,False
248,229,HoundoomMega Houndoom,Dark,Fire,600,75,90,90,140,90,115,2,False
268,248,TyranitarMega Tyranitar,Rock,Dark,700,100,164,150,95,120,71,2,False
275,254,SceptileMega Sceptile,Grass,Dragon,630,70,110,75,145,85,145,3,False
279,257,BlazikenMega Blaziken,Fire,Fighting,630,80,160,80,130,80,100,3,False
283,260,SwampertMega Swampert,Water,Ground,635,100,150,110,95,110,70,3,False
306,282,GardevoirMega Gardevoir,Psychic,Fairy,618,68,85,65,165,135,100,3,False
327,302,SableyeMega Sableye,Dark,Ghost,480,50,85,125,85,115,20,3,False
329,303,MawileMega Mawile,Steel,Fairy,480,50,105,125,55,95,50,3,False
333,306,AggronMega Aggron,Steel,NaN,630,70,140,230,60,80,50,3,False
336,308,MedichamMega Medicham,Fighting,Psychic,510,60,100,85,80,85,100,3,False
339,310,ManectricMega Manectric,Electric,NaN,575,70,75,80,135,80,135,3,False
349,319,SharpedoMega Sharpedo,Water,Dark,560,70,140,70,110,65,105,3,False
354,323,CameruptMega Camerupt,Fire,Ground,560,70,120,100,145,105,20,3,False
366,334,AltariaMega Altaria,Dragon,Fairy,590,75,110,110,110,105,80,3,False
387,354,BanetteMega Banette,Ghost,NaN,555,64,165,75,93,83,75,3,False
393,359,AbsolMega Absol,Dark,NaN,565,65,150,60,115,60,115,3,False
397,362,GlalieMega Glalie,Ice,NaN,580,80,120,80,120,80,100,3,False
409,373,SalamenceMega Salamence,Dragon,Flying,700,95,145,130,120,90,120,3,False
413,376,MetagrossMega Metagross,Steel,Psychic,700,80,145,150,105,110,110,3,False
418,380,LatiasMega Latias,Dragon,Psychic,700,80,100,120,140,150,110,3,True
420,381,LatiosMega Latios,Dragon,Psychic,700,80,130,100,160,120,110,3,True
426,384,RayquazaMega Rayquaza,Dragon,Flying,780,105,180,100,180,100,115,3,True
476,428,LopunnyMega Lopunny,Normal,Fighting,580,65,136,94,54,96,135,4,False
494,445,GarchompMega Garchomp,Dragon,Ground,700,108,170,115,120,95,92,4,False
498,448,LucarioMega Lucario,Fighting,Steel,625,70,145,88,140,70,112,4,False
511,460,AbomasnowMega Abomasnow,Grass,Ice,594,90,132,105,132,105,30,4,False
527,475,GalladeMega Gallade,Psychic,Fighting,618,68,165,95,65,115,110,4,False
591,531,AudinoMega Audino,Normal,Fairy,545,103,60,126,80,126,50,5,False
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True

In [8]:
#I create column NewName with the change required:
pokemon['NewName']=pokemon['Name'].str.replace('[A-Z][a-z]+Mega','Mega')

C:\Users\patri\AppData\Local\Temp/ipykernel_12296/1887172928.py:2: FutureWarning: The default value of regex will change from True to False in a future version.
  pokemon['NewName']=pokemon['Name'].str.replace('[A-Z][a-z]+Mega','Mega')

In [9]:
#Check Names vs NewNames column:
pokemon[['Name','NewName']][pokemon['Name'].str.contains('Mega')]

                          Name           NewName
3        VenusaurMega Venusaur     Mega Venusaur
7    CharizardMega Charizard X  Mega Charizard X
8    CharizardMega Charizard Y  Mega Charizard Y
12     BlastoiseMega Blastoise    Mega Blastoise
19       BeedrillMega Beedrill     Mega Beedrill
23         PidgeotMega Pidgeot      Mega Pidgeot
71       AlakazamMega Alakazam     Mega Alakazam
87         SlowbroMega Slowbro      Mega Slowbro
102          GengarMega Gengar       Mega Gengar
124  KangaskhanMega Kangaskhan   Mega Kangaskhan
137          PinsirMega Pinsir       Mega Pinsir
141      GyaradosMega Gyarados     Mega Gyarados
154  AerodactylMega Aerodactyl   Mega Aerodactyl
163        MewtwoMega Mewtwo X     Mega Mewtwo X
164        MewtwoMega Mewtwo Y     Mega Mewtwo Y
168                   Meganium          Meganium
196      AmpharosMega Ampharos     Mega Ampharos
224        SteelixMega Steelix      Mega Steelix
229          ScizorMega Scizor       Mega Scizor
232    HeracrossMega Heracross    Mega Heracross
248      HoundoomMega Houndoom     Mega Houndoom
268    TyranitarMega Tyranitar    Mega Tyranitar
275      SceptileMega Sceptile     Mega Sceptile
279      BlazikenMega Blaziken     Mega Blaziken
283      SwampertMega Swampert     Mega Swampert
306    GardevoirMega Gardevoir    Mega Gardevoir
327        SableyeMega Sableye      Mega Sableye
329          MawileMega Mawile       Mega Mawile
333          AggronMega Aggron       Mega Aggron
336      MedichamMega Medicham     Mega Medicham
339    ManectricMega Manectric    Mega Manectric
349      SharpedoMega Sharpedo     Mega Sharpedo
354      CameruptMega Camerupt     Mega Camerupt
366        AltariaMega Altaria      Mega Altaria
387        BanetteMega Banette      Mega Banette
393            AbsolMega Absol        Mega Absol
397          GlalieMega Glalie       Mega Glalie
409    SalamenceMega Salamence    Mega Salamence
413    MetagrossMega Metagross    Mega Metagross
418          LatiasMega Latias       Mega Latias
420          LatiosMega Latios       Mega Latios
426      RayquazaMega Rayquaza     Mega Rayquaza
476        LopunnyMega Lopunny      Mega Lopunny
494      GarchompMega Garchomp     Mega Garchomp
498        LucarioMega Lucario      Mega Lucario
511    AbomasnowMega Abomasnow    Mega Abomasnow
527        GalladeMega Gallade      Mega Gallade
591          AudinoMega Audino       Mega Audino
796        DiancieMega Diancie      Mega Diancie

In [10]:
#I update Name column to NewName values:
pokemon['Name']= pokemon['NewName']

In [11]:
#Then I get rid of NewName column:
pokemon = pokemon.drop('NewName',axis=1)

#### Create a new column called `A/D Ratio` whose value equals to `Attack` devided by `Defense`.

For instance, if a pokemon has the Attack score 49 and Defense score 49, the corresponding `A/D Ratio` is 49/49=1.

In [12]:
# your code here
pokemon['A/D Ratio']= pokemon['Attack']/pokemon['Defense']
pokemon[['A/D Ratio','Attack','Defense']]

     A/D Ratio  Attack  Defense
0     1.000000      49       49
1     0.984127      62       63
2     0.987952      82       83
3     0.813008     100      123
4     1.209302      52       43
..         ...     ...      ...
795   0.666667     100      150
796   1.454545     160      110
797   1.833333     110       60
798   2.666667     160       60
799   0.916667     110      120

[800 rows x 3 columns]

#### Identify the pokemon with the highest `A/D Ratio`.

In [13]:
# your code here
pokemon['A/D Ratio'].max() #this is the max value for A/D Ratio

#this is the row for the max value of AD Ratio:
pokemon[pokemon['A/D Ratio']==pokemon['A/D Ratio'].max()]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio
429,386,DeoxysAttack Forme,Psychic,NaN,600,50,180,20,180,20,150,3,True,9.0

#### Identify the pokemon with the lowest A/D Ratio.

In [14]:
# your code here
pokemon[pokemon['A/D Ratio']==pokemon['A/D Ratio'].min()]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio
230,213,Shuckle,Bug,Rock,505,20,10,230,10,230,5,2,False,0.043478

#### Create a new column called `Combo Type` whose value combines `Type 1` and `Type 2`.

Rules:

* If both `Type 1` and `Type 2` have valid values, the `Combo Type` value should contain both values in the form of `<Type 1> <Type 2>`. For example, if `Type 1` value is `Grass` and `Type 2` value is `Poison`, `Combo Type` will be `Grass-Poison`.

* If `Type 1` has valid value but `Type 2` is not, `Combo Type` will be the same as `Type 1`. For example, if `Type 1` is `Fire` whereas `Type 2` is `NaN`, `Combo Type` will be `Fire`.

In [15]:
# your code here
#I take a look first into both columns:
pokemon[['Type 1','Type 2']]

      Type 1  Type 2
0      Grass  Poison
1      Grass  Poison
2      Grass  Poison
3      Grass  Poison
4       Fire     NaN
..       ...     ...
795     Rock   Fairy
796     Rock   Fairy
797  Psychic   Ghost
798  Psychic    Dark
799     Fire   Water

[800 rows x 2 columns]

In [17]:
#Columns 'Type 1','Type 2' where type 1 or type 2 is equal NaN:
#pokemon[['#','Type 1','Type 2']][pokemon['Type 1'].isnull() | pokemon['Type 2'].isnull()]
pokemon[['#','Type 1','Type 2']][pokemon['Type 1'].isnull() ] #empty

Empty DataFrame
Columns: [#, Type 1, Type 2]
Index: []

In [20]:
#USING A FUNCTION:

def BuildComboTypeRow(row):
    import math
    if type(row['Type 2'])==float and math.isnan(row['Type 2']): #Despite row['Type 2'] is a string, Nan values are actually floats
        val = row['Type 1']
    else:
        val = row['Type 1'] + '-' + str(row['Type 2'])
    return val

pokemon['Combo Type'] = pokemon.apply(BuildComboTypeRow, axis=1)

In [21]:
# I was trying a different way, but I couldn't make it :( 
#df['Price'] = [1500 if x =='Music' else 800 for x in df['Event']]
#pokemon['Combo Type 2'] = [x if type(y)==float and math.isnan(y) else x for x,y in pokemon[['Type 1','Type 2']]]
#pokemon['Combo Type 2'] = [x if y=='dfsf' else x for x,y in pokemon[['Type 1','Type 2']]]

#### Identify the pokemon whose `A/D Ratio` are among the top 5.

In [22]:
# your code here
pokemon.sort_values(by=['A/D Ratio'], ascending=False).head(5)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio,Combo Type
429,386,DeoxysAttack Forme,Psychic,NaN,600,50,180,20,180,20,150,3,True,9.000,Psychic
347,318,Carvanha,Water,Dark,305,45,90,20,65,20,65,3,False,4.500,Water-Dark
19,15,Mega Beedrill,Bug,Poison,495,65,150,40,15,80,145,1,False,3.750,Bug-Poison
453,408,Cranidos,Rock,NaN,350,67,125,40,30,30,58,4,False,3.125,Rock
348,319,Sharpedo,Water,Dark,460,70,120,40,95,40,95,3,False,3.000,Water-Dark

#### For the 5 pokemon printed above, aggregate `Combo Type` and use a list to store the unique values.

Your end product is a list containing the distinct `Combo Type` values of the 5 pokemon with the highest `A/D Ratio`.

In [28]:
# your code here
best_combo_Type=list((pokemon.sort_values(by=['A/D Ratio'], ascending=False).head(5))['Combo Type'])
best_combo_Type

['Psychic', 'Water-Dark', 'Bug-Poison', 'Rock', 'Water-Dark']

#### For each of the `Combo Type` values obtained from the previous question, calculate the mean scores of all numeric fields across all pokemon.

Your output should look like below:

![Aggregate](../images/aggregated-mean.png)

In [33]:
# your code here
#print(data[data['name'].isin(list1)])
combo_type_filtered_pd = pokemon[pokemon['Combo Type'].isin(best_combo_Type)]
combo_type_filtered_pd

combo_type_filtered_pd.groupby(['Combo Type']).agg({'Total':'mean','HP':'mean','Attack':'mean','Defense':'mean','Sp. Atk':'mean'
                                                    ,'Sp. Def':'mean','Speed':'mean','Generation':'mean','A/D Ratio':'mean'})

,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,A/D Ratio
Combo Type,,,,,,,,,
Bug-Poison,347.916667,53.750000,68.333333,58.083333,42.500000,59.333333,65.916667,2.333333,1.315989
Psychic,464.552632,72.552632,64.947368,67.236842,98.552632,82.394737,78.868421,3.342105,1.164196
Rock,409.444444,67.111111,103.333333,107.222222,40.555556,58.333333,32.888889,3.888889,1.260091
Water-Dark,493.833333,69.166667,120.000000,65.166667,88.833333,63.500000,87.166667,3.166667,2.291949